/* dsh-rewind client bundle — generated by scripts/build.mjs from src/client/ */
window.__ModuleLoader__.load({
  id: "dsh-rewind-plugin",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name2 in all)
    __defProp(target, name2, { get: all[name2], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client/index.ts
var index_exports = {};
__export(index_exports, {
  apply: () => apply,
  hiddenSeqsOf: () => hiddenSeqsOf,
  inject: () => inject,
  name: () => name,
  targetSeqOfArgs: () => targetSeqOfArgs
});
module.exports = __toCommonJS(index_exports);

// src/client/hidden.ts
function resolveChatWatch(resolveView, sessionId, cb) {
  const view = resolveView(sessionId);
  return view?.subscribe?.(cb) ?? (() => {
  });
}
function chatSnapshotOf(chatView) {
  return chatView?.getSnapshot() ?? void 0;
}
function messageTextAt(chat, seq) {
  if (chat === void 0) return void 0;
  for (const key of chat.order) {
    const node = chat.nodes.get(key);
    if (node === void 0 || node.kind !== "user" && node.kind !== "steering") continue;
    const data = node.data;
    if (data.seq === seq) {
      return data.content?.map((block) => block.type === "text" && typeof block.text === "string" ? block.text : "").join("");
    }
  }
  return void 0;
}
function targetSeqOfArgs(args) {
  if (args === void 0 || args === null) return void 0;
  const match = args.match(/@(\d+)/);
  return match !== null ? Number(match[1]) : void 0;
}
function isExecutedRewindCommand(node, seq) {
  if (node.name !== "rewind" || node.outcome?.kind !== "success") return false;
  if (node.outcome.sourceEventSeq === void 0) return false;
  const args = node.args ?? "";
  return new RegExp(`(?:^|\\s)@${seq}(?:\\s|$)`).test(args);
}
function hasFileImpact(text) {
  if (text === void 0) return true;
  const match = text.match(/impact=(\d+)/);
  if (match !== null) return Number(match[1]) > 0;
  return false;
}
function isPreviewCommand(command) {
  return (command.args ?? "").includes("preview");
}
function isCandidateCommand(command) {
  return (command.args ?? "").includes("__candidates");
}
function hiddenSeqsOf(snap) {
  const hidden = /* @__PURE__ */ new Set();
  const spans = [];
  for (const key of snap.order) {
    const node = snap.nodes.get(key);
    if (node === void 0 || node.kind !== "command") continue;
    const command = node.data;
    if (command.name !== "rewind") continue;
    if (isPreviewCommand(command) || isCandidateCommand(command)) {
      hidden.add(command.seq);
      continue;
    }
    if (command.outcome?.kind !== "success") continue;
    const marker = command.outcome.sourceEventSeq;
    if (marker === void 0) continue;
    hidden.add(command.seq);
    const target = targetSeqOfArgs(command.args);
    if (target !== void 0) {
      spans.push({ start: target, end: marker });
    }
  }
  for (const key of snap.order) {
    const node = snap.nodes.get(key);
    if (node === void 0) continue;
    const anchor = node.anchorSeq;
    if (spans.some((span) => anchor >= span.start && anchor <= span.end)) {
      hidden.add(anchor);
    }
  }
  return hidden;
}

// src/client/candidates.ts
var PREVIEW_CHARS = 80;
var DEFAULT_CANDIDATE_LIMIT = 100;
function messagePreviewOf(message) {
  const text = message.content.map((block) => block.type === "text" && typeof block.text === "string" ? block.text : "").join("").replace(/\s+/g, " ").trim();
  return text.length <= PREVIEW_CHARS ? text : `${text.slice(0, PREVIEW_CHARS - 1)}\u2026`;
}
function formatCandidateTime(time) {
  const d = new Date(time);
  const hh = String(d.getHours()).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  return `${hh}:${mm}`;
}
function rewindCandidatesOf(snap, hidden, limit = DEFAULT_CANDIDATE_LIMIT) {
  const candidates = [];
  for (let i = snap.order.length - 1; i >= 0 && candidates.length < limit; i--) {
    const key = snap.order[i];
    if (key === void 0) continue;
    const node = snap.nodes.get(key);
    if (node === void 0 || node.kind !== "user" && node.kind !== "steering") continue;
    if (hidden.has(node.anchorSeq ?? node.data.seq)) continue;
    candidates.push({
      seq: node.data.seq,
      time: node.data.time,
      preview: messagePreviewOf(node.data)
    });
  }
  return candidates;
}
function rewindCandidatesOfChat(snap) {
  return rewindCandidatesOf(snap, hiddenSeqsOf(snap));
}
var CANDIDATE_LIST_HEADER = "candidates=";
function rewindCandidatesFromHostText(text) {
  if (!text.startsWith(CANDIDATE_LIST_HEADER)) return [];
  const lines = text.split("\n").slice(1);
  const candidates = [];
  for (const line of lines) {
    if (line === "") continue;
    const parts = line.split("	");
    if (parts.length !== 3) continue;
    const seq = Number(parts[0]);
    const time = Number(parts[1]);
    const preview = parts[2] ?? "";
    if (!Number.isSafeInteger(seq) || !Number.isFinite(time)) continue;
    candidates.push({ seq, time, preview });
  }
  return candidates;
}
function rewindOptionsFromCandidates(candidates, t) {
  return candidates.map((candidate) => ({
    id: String(candidate.seq),
    label: candidate.preview || t("popover.noText"),
    detail: formatCandidateTime(candidate.time)
  }));
}

// src/client/log.ts
var NS = "dsh-rewind";
var DEBUG_KEY = "dsh-rewind.debug";
var ALWAYS_ON = /* @__PURE__ */ new Set(["error", "warn"]);
function switchValue() {
  try {
    return window.localStorage.getItem(DEBUG_KEY) ?? "";
  } catch {
    return "";
  }
}
function matches(value, ns) {
  for (const entry of value.split(",")) {
    const part = entry.trim();
    if (part === "") continue;
    if (part === "*" || part === `${NS}*`) return true;
    if (part.endsWith("*")) {
      if (ns.startsWith(part.slice(0, -1))) return true;
    } else if (ns === part) {
      return true;
    }
  }
  return false;
}
function tag(scope) {
  return `[${NS}:${scope}]`;
}
function log(level, scope, message, data) {
  if (ALWAYS_ON.has(level)) {
    console[level](tag(scope), message, data);
    return;
  }
  if (!matches(switchValue(), `${NS}:${scope}`)) return;
  console.info(tag(scope), message, data);
}
var rewindLog = {
  error: (scope, message, data) => log("error", scope, message, data),
  warn: (scope, message, data) => log("warn", scope, message, data),
  info: (scope, message, data) => log("info", scope, message, data),
  debug: (scope, message, data) => log("debug", scope, message, data)
};

// src/client/styles.ts
var CLASS = {
  button: "dsh-rewind-btn",
  popover: "dsh-rewind-popover",
  popoverTitle: "dsh-rewind-popover-title",
  popoverTarget: "dsh-rewind-popover-target",
  popoverOption: "dsh-rewind-popover-option",
  popoverOptionLabel: "dsh-rewind-popover-option-label",
  popoverOptionHint: "dsh-rewind-popover-option-hint",
  popoverImpact: "dsh-rewind-popover-impact",
  popoverActions: "dsh-rewind-popover-actions",
  popoverPrimary: "dsh-rewind-popover-primary",
  popoverGhost: "dsh-rewind-popover-ghost",
  guardHint: "dsh-rewind-guard-hint"
};
var REWIND_ICON_SVG = [
  '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">',
  '  <path d="M6.5 2.5 2.5 6.5l4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>',
  '  <path d="M2.5 6.5h7a4 4 0 0 1 4 4v1.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>',
  "</svg>"
].join("");
var STYLE = `
.dsh-rewind-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  padding: 6px;
  border: none;
  border-radius: 28px;
  background: transparent;
  color: var(--dsw-alias-label-tertiary);
  cursor: pointer;
}
.dsh-rewind-btn:hover {
  background: var(--dsw-alias-interactive-bg-hover);
  color: var(--dsw-alias-label-secondary);
}

.dsh-rewind-popover {
  position: fixed;
  z-index: 1000;
  width: 288px;
  padding: 12px;
  border: 1px solid var(--dsw-alias-border-l2);
  border-radius: 12px;
  background: var(--dsw-specific-menu, var(--dsw-alias-bg-layer-3));
  box-shadow: var(--dsw-shadow-lv3);
  font-size: 14px;
  line-height: 20px;
  color: var(--dsw-alias-label-primary);
}
.dsh-rewind-popover-title {
  font-size: 14px;
  font-weight: 600;
  line-height: 20px;
}
.dsh-rewind-popover-target {
  margin: 4px 0 10px;
  font-size: 12px;
  line-height: 16px;
  color: var(--dsw-alias-label-tertiary);
  word-break: break-all;
}
.dsh-rewind-popover-option {
  display: flex;
  flex-direction: column;
  gap: 2px;
  width: 100%;
  margin: 0 0 6px;
  padding: 8px 10px;
  border: 1px solid transparent;
  border-radius: 8px;
  background: transparent;
  color: inherit;
  font: inherit;
  text-align: left;
  cursor: pointer;
}
.dsh-rewind-popover-option:hover {
  background: var(--dsw-alias-interactive-bg-hover);
}
.dsh-rewind-popover-option:disabled {
  opacity: 0.5;
  cursor: default;
}
.dsh-rewind-popover-option-label {
  font-weight: 500;
}
.dsh-rewind-popover-option-hint {
  font-size: 12px;
  line-height: 16px;
  color: var(--dsw-alias-label-tertiary);
}
.dsh-rewind-popover-impact {
  margin: 4px 0 10px;
  padding: 8px 10px;
  border-radius: 8px;
  background: var(--dsw-alias-interactive-bg-hover);
  font-size: 12px;
  line-height: 16px;
  color: var(--dsw-alias-label-secondary);
  white-space: pre-wrap;
  max-height: 160px;
  overflow: auto;
}
.dsh-rewind-popover-actions {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}
.dsh-rewind-popover-primary,
.dsh-rewind-popover-ghost {
  padding: 5px 12px;
  border: none;
  border-radius: 8px;
  font: inherit;
  font-size: 13px;
  line-height: 18px;
  cursor: pointer;
}
.dsh-rewind-popover-primary {
  background: var(--dsw-alias-button-primary-fill);
  color: var(--dsw-alias-label-primary-foreground);
}
.dsh-rewind-popover-primary:hover:not(:disabled) {
  background: var(--dsw-alias-button-primary-hover);
}
.dsh-rewind-popover-primary:disabled {
  opacity: 0.5;
  cursor: default;
}
.dsh-rewind-popover-ghost {
  background: transparent;
  color: var(--dsw-alias-label-secondary);
}
.dsh-rewind-popover-ghost:hover {
  background: var(--dsw-alias-interactive-bg-hover);
}

.dsh-rewind-guard-hint {
  position: fixed;
  z-index: 1000;
  max-width: min(440px, calc(100vw - 24px));
  padding: 8px 12px;
  border: 1px solid var(--dsw-alias-border-l2);
  border-radius: 10px;
  background: var(--dsw-specific-menu, var(--dsw-alias-bg-layer-3));
  box-shadow: var(--dsw-shadow-lv3);
  font-size: 13px;
  line-height: 18px;
  color: var(--dsw-alias-label-primary);
  pointer-events: none;
}

/* ---- Snapshot-cleanup settings card (mirrors the harness PluginCard look) ---- */
/* Standardized on the 0.1.2 harness card look (border-radius 16px + 0.5px
   border-l4, 0.5px internal separators). */
.dsh-rewind-cleanup-card {
  list-style: none;
  border: 0.5px solid var(--dsw-alias-border-l4);
  border-radius: 16px;
  background: var(--dsw-alias-bg-layer-3);
  transition: border-color .16s, background .16s;
}
.dsh-rewind-cleanup-card:hover {
  border-color: var(--dsw-alias-label-dimmed);
}
.dsh-rewind-cleanup-card-open {
  background: var(--dsw-alias-bg-layer-2);
  border-color: var(--dsw-alias-label-dimmed);
}
.dsh-rewind-cleanup-header {
  width: 100%;
  appearance: none;
  border: 0;
  background: none;
  font: inherit;
  color: inherit;
  text-align: left;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 14px 16px;
  border-radius: 12px;
}
.dsh-rewind-cleanup-header:focus-visible {
  outline: 2px solid var(--dsw-alias-brand-primary);
  outline-offset: -2px;
}
.dsh-rewind-cleanup-head-text {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.dsh-rewind-cleanup-name {
  font-size: 15px;
  font-weight: 600;
  line-height: 1.4;
  color: var(--dsw-alias-label-primary);
}
.dsh-rewind-cleanup-desc {
  font-size: 13px;
  line-height: 1.5;
  color: var(--dsw-alias-label-tertiary);
}
.dsh-rewind-cleanup-chevron {
  flex: none;
  color: var(--dsw-alias-label-tertiary);
  transition: transform .16s;
}
.dsh-rewind-cleanup-chevron-open {
  transform: rotate(180deg);
}
.dsh-rewind-cleanup-pending {
  flex: none;
  border-radius: 999px;
  padding: 1px 8px;
  font-size: 11px;
  line-height: 17px;
  font-weight: 500;
  white-space: nowrap;
  background: var(--dsw-alias-bg-module-platform);
  color: var(--dsw-alias-label-secondary);
}
.dsh-rewind-cleanup-body {
  border-top: 0.5px solid var(--dsw-alias-border-l2);
  margin: 0 16px;
  padding: 0 0 8px;
}
.dsh-rewind-cleanup-readonly {
  margin: 12px 0 0;
  font-size: 12px;
  line-height: 1.5;
  color: var(--dsw-alias-label-tertiary);
}
.dsh-rewind-cleanup-permission {
  display: grid;
  gap: 6px;
  padding: 12px 0;
}
.dsh-rewind-cleanup-field {
  display: flex;
  flex-direction: column;
  gap: 6px;
  padding: 12px 0;
}
.dsh-rewind-cleanup-field + .dsh-rewind-cleanup-field {
  border-top: 0.5px solid var(--dsw-alias-border-l2);
}
/* Auto-cleanup (permission) block and the max-age field are consecutive control
 * sections of the open card \u2014 give them the same 0.5px divider the harness gives
 * every pair of config fields (fields.module.css field + field). */
.dsh-rewind-cleanup-permission + .dsh-rewind-cleanup-field {
  border-top: 0.5px solid var(--dsw-alias-border-l2);
}
.dsh-rewind-cleanup-head {
  display: flex;
  align-items: center;
  gap: 8px;
}
.dsh-rewind-cleanup-label {
  flex: 1;
  min-width: 0;
  font-size: 13px;
  font-weight: 500;
  line-height: 1.5;
  color: var(--dsw-alias-label-primary);
}
.dsh-rewind-cleanup-hint {
  margin: 0;
  font-size: 12px;
  line-height: 1.5;
  color: var(--dsw-alias-label-tertiary);
}
.dsh-rewind-cleanup-error {
  margin: 0;
  font-size: 12px;
  line-height: 1.5;
  color: var(--dsw-alias-label-error);
}
/* Switch row: label left, role=switch button right, hint below (Subagent module).
 * The track mirrors the harness ui-primitives Switch (0.1.3-alpha.2 line): the
 * on/off appearance keys off aria-checked rather than a parallel class, so the
 * visual state cannot disagree with the state assistive technology reads, and
 * corner-shape: round opts the capsule track out of the global superellipse
 * (which would square the capsule ends off against the round thumb inside). */
.dsh-rewind-cleanup-toggle-row {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 16px;
  font-size: 13px;
  line-height: 1.5;
  color: var(--dsw-alias-label-primary);
}
.dsh-rewind-cleanup-toggle-label {
  flex: 1;
  min-width: 0;
}
.dsh-rewind-cleanup-switch {
  box-sizing: border-box;
  position: relative;
  flex: 0 0 auto;
  width: 36px;
  height: 20px;
  padding: 2px;
  border: 0;
  border-radius: 10px;
  corner-shape: round;
  background: var(--dsw-alias-border-l3);
  cursor: pointer;
}
.dsh-rewind-cleanup-switch[aria-checked='true'] {
  background: var(--dsw-alias-brand-primary);
}
.dsh-rewind-cleanup-switch:disabled {
  cursor: default;
  opacity: 0.5;
}
.dsh-rewind-cleanup-switch:focus-visible {
  outline: 2px solid var(--dsw-alias-brand-primary);
  outline-offset: 2px;
}
.dsh-rewind-cleanup-thumb {
  display: block;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  corner-shape: round;
  background: var(--dsw-alias-label-primary-foreground);
  transition: transform 120ms ease;
}
.dsh-rewind-cleanup-switch[aria-checked='true'] .dsh-rewind-cleanup-thumb {
  transform: translateX(16px);
}
.dsh-rewind-cleanup-input {
  box-sizing: border-box;
  height: 34px;
  padding: 0 12px;
  border: 0.5px solid var(--dsw-alias-border-l4);
  border-radius: 8px;
  background: var(--dsw-alias-bg-layer-3);
  font: inherit;
  font-size: 13px;
  line-height: 1.5;
  color: var(--dsw-alias-label-primary);
}
.dsh-rewind-cleanup-input:focus-visible {
  outline: none;
  border-color: var(--dsw-alias-brand-primary);
}
.dsh-rewind-cleanup-input:disabled {
  color: var(--dsw-alias-label-tertiary);
  cursor: default;
}
.dsh-rewind-cleanup-input-invalid {
  border-color: var(--dsw-alias-label-error);
}
.dsh-rewind-cleanup-footer {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 8px;
  padding: 12px 0 4px;
  border-top: 0.5px solid var(--dsw-alias-border-l2);
}
.dsh-rewind-cleanup-failed {
  flex: 1;
  min-width: 0;
  margin: 0;
  font-size: 12px;
  line-height: 1.5;
  color: var(--dsw-alias-label-error);
}
.dsh-rewind-cleanup-discard,
.dsh-rewind-cleanup-save {
  appearance: none;
  border: 1px solid transparent;
  border-radius: 8px;
  padding: 5px 14px;
  font: inherit;
  font-size: 13px;
  line-height: 1.5;
  cursor: pointer;
}
.dsh-rewind-cleanup-discard {
  border-color: var(--dsw-alias-border-l2);
  background: none;
  color: var(--dsw-alias-label-secondary);
}
.dsh-rewind-cleanup-discard:hover:not(:disabled) {
  color: var(--dsw-alias-label-primary);
  border-color: var(--dsw-alias-label-dimmed);
}
.dsh-rewind-cleanup-save {
  background: var(--dsw-alias-label-primary);
  color: var(--dsw-alias-bg-layer-3);
}
.dsh-rewind-cleanup-discard:disabled,
.dsh-rewind-cleanup-save:disabled {
  opacity: 0.4;
  cursor: default;
}
.dsh-rewind-cleanup-discard:focus-visible,
.dsh-rewind-cleanup-save:focus-visible {
  outline: 2px solid var(--dsw-alias-brand-primary);
  outline-offset: 1px;
}
`;

// src/client/popover.ts
var popoverEl = null;
var disposeOutside = null;
function closePopover() {
  if (popoverEl !== null) {
    popoverEl.remove();
    popoverEl = null;
  }
  if (disposeOutside !== null) {
    disposeOutside();
    disposeOutside = null;
  }
}
function formatTarget(t, seq, time, preview) {
  const d = new Date(time);
  const hh = String(d.getHours()).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  const previewText = preview.length > 0 ? preview : t("popover.noText");
  return `seq ${seq} \xB7 ${hh}:${mm} \xB7 ${previewText}`;
}
function parseImpactList(text) {
  const restores = [];
  const deletes = [];
  for (const line of text.split("\n")) {
    if (line.startsWith("restore:")) restores.push(line.slice("restore:".length));
    else if (line.startsWith("delete:")) deletes.push(line.slice("delete:".length));
  }
  return { restores, deletes };
}
function findCommand(chat, match) {
  if (chat === void 0) return void 0;
  let found;
  for (const key of chat.order) {
    const node = chat.nodes.get(key);
    if (node !== void 0 && node.kind === "command") {
      const command = node.data;
      if (match(command)) found = command;
    }
  }
  return found;
}
function knownCommandSeqs(session, chatOf, match) {
  const known = /* @__PURE__ */ new Set();
  const chat = chatOf(session);
  if (chat === void 0) return known;
  for (const key of chat.order) {
    const node = chat.nodes.get(key);
    if (node !== void 0 && node.kind === "command") {
      const command = node.data;
      if (match(command)) known.add(command.seq);
    }
  }
  return known;
}
function waitForCommand(session, chatOf, match, timeoutMs = 8e3, watch) {
  return new Promise((resolve) => {
    let settled = false;
    const settle = (value) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      unsubscribe();
      resolve(value);
    };
    const check = () => {
      const node = findCommand(chatOf(session), match);
      if (node?.outcome !== null && node?.outcome !== void 0) {
        settle({ kind: node.outcome.kind, text: node.outcome.text });
      }
    };
    const unsubscribe = watch(check);
    const timer = setTimeout(() => settle(null), timeoutMs);
    check();
  });
}
function isPreviewFor(node, seq) {
  const args = node.args ?? "";
  return node.name === "rewind" && args.includes("preview") && new RegExp(`(?:^|\\s)@${seq}(?=\\s|$)`).test(args);
}
async function previewImpact(session, chatOf, seq, watch) {
  const known = knownCommandSeqs(session, chatOf, (node) => isPreviewFor(node, seq));
  let result;
  try {
    result = await session.command(`/rewind preview @${seq} both`);
  } catch (error) {
    rewindLog.warn("preview", `preview command threw for @${seq}`, error);
    return { kind: "error", text: error instanceof Error ? error.message : String(error) };
  }
  if (!result.ok) {
    rewindLog.warn("preview", `preview command rejected for @${seq}`, result.error);
    return { kind: "error", text: `${result.error.code}: ${result.error.message}` };
  }
  if (result.value?.matched !== true) {
    rewindLog.warn("preview", `preview command was not matched for @${seq}`);
    return { kind: "error", text: "the rewind command is not registered on this host" };
  }
  return waitForCommand(session, chatOf, (node) => isPreviewFor(node, seq) && !known.has(node.seq), 8e3, watch);
}
function el(tag2, className, text) {
  const node = document.createElement(tag2);
  node.className = className;
  if (text !== void 0) node.textContent = text;
  return node;
}
function modeOption(label, hint, onClick) {
  const button = document.createElement("button");
  button.type = "button";
  button.className = CLASS.popoverOption;
  const labelEl = el("span", CLASS.popoverOptionLabel, label);
  const hintEl = el("span", CLASS.popoverOptionHint, hint);
  button.append(labelEl, hintEl);
  button.addEventListener("click", onClick);
  return button;
}
function focusableButtons(root) {
  return Array.from(root.querySelectorAll("button")).filter((button) => !button.disabled && !button.classList.contains(CLASS.popoverGhost));
}
function focusFirst(root) {
  focusableButtons(root)[0]?.focus();
}
function moveFocus(root, dir) {
  const buttons = focusableButtons(root);
  if (buttons.length === 0) return;
  const active = document.activeElement;
  const index = active instanceof HTMLButtonElement ? buttons.indexOf(active) : -1;
  const next = index === -1 ? dir === 1 ? 0 : buttons.length - 1 : (index + dir + buttons.length) % buttons.length;
  buttons[next]?.focus();
}
function renderImpactStep(root, opts, back, cached) {
  const { session, seq, t } = opts;
  const impact = el("div", CLASS.popoverImpact, t("popover.impact.loading"));
  const actions = el("div", CLASS.popoverActions);
  const backButton = document.createElement("button");
  backButton.type = "button";
  backButton.className = CLASS.popoverGhost;
  backButton.textContent = t("popover.back");
  backButton.addEventListener("click", back);
  actions.append(backButton);
  const confirm = document.createElement("button");
  confirm.type = "button";
  confirm.className = CLASS.popoverPrimary;
  confirm.textContent = t("popover.confirm");
  confirm.disabled = true;
  actions.append(confirm);
  root.replaceChildren(impact, actions);
  focusFirst(root);
  void (async () => {
    const outcome = cached ?? await previewImpact(session, opts.chatOf, seq, (cb) => opts.watchChat(session.sessionId, cb));
    if (outcome === null) {
      impact.textContent = t("popover.impact.failed", { message: "preview command failed or timed out" });
      return;
    }
    if (outcome.kind === "error") {
      impact.textContent = t("popover.impact.failed", { message: outcome.text ?? "unknown error" });
      return;
    }
    if (outcome.text === void 0) {
      impact.textContent = t("popover.impact.none");
    } else {
      const { restores, deletes } = parseImpactList(outcome.text);
      if (restores.length === 0 && deletes.length === 0) {
        impact.textContent = t("popover.impact.none");
      } else {
        const lines = [
          ...restores.map((path) => t("popover.impact.restore", { path })),
          ...deletes.map((path) => t("popover.impact.delete", { path }))
        ];
        impact.textContent = lines.join("\n");
      }
    }
    confirm.disabled = false;
    confirm.focus();
    confirm.addEventListener("click", () => {
      closePopover();
      opts.onRewind("both");
    });
  })().catch(() => {
    impact.textContent = t("popover.impact.failed", { message: "unexpected error" });
  });
}
function mountShell(root, anchor, onKeyDown) {
  const position = () => {
    const rect = anchor.getBoundingClientRect();
    const gap = 4;
    const height = root.offsetHeight;
    const top = rect.bottom + gap + height <= window.innerHeight - 8 ? rect.bottom + gap : Math.max(8, rect.top - gap - height);
    root.style.top = `${Math.round(top)}px`;
    root.style.left = `${Math.round(Math.min(rect.right, window.innerWidth - 8 - root.offsetWidth))}px`;
  };
  const onPointerDown = (event) => {
    const target = event.target;
    if (root.contains(target) || anchor.contains(target)) return;
    closePopover();
  };
  const deferred = setTimeout(() => {
    document.addEventListener("pointerdown", onPointerDown);
    document.addEventListener("keydown", onKeyDown, true);
  }, 0);
  const dispose = () => {
    clearTimeout(deferred);
    document.removeEventListener("pointerdown", onPointerDown);
    document.removeEventListener("keydown", onKeyDown, true);
  };
  document.body.append(root);
  position();
  return { position, dispose };
}
function openRetractPopover(opts) {
  closePopover();
  const { preview, anchor, t, retract, onRetract } = opts;
  if (retract === void 0 || onRetract === void 0) return;
  const root = el("div", CLASS.popover);
  root.setAttribute("role", "dialog");
  root.setAttribute("aria-label", t("popover.retract.title"));
  const onKeyDown = (event) => {
    if (event.key === "ArrowDown") {
      event.preventDefault();
      event.stopPropagation();
      moveFocus(root, 1);
      return;
    }
    if (event.key === "ArrowUp") {
      event.preventDefault();
      event.stopPropagation();
      moveFocus(root, -1);
      return;
    }
    if (event.key === "Escape") {
      event.preventDefault();
      event.stopPropagation();
      closePopover();
    }
  };
  const previewText = preview.length > 0 ? preview : t("popover.noText");
  const actions = el("div", CLASS.popoverActions);
  const confirm = document.createElement("button");
  confirm.type = "button";
  confirm.className = CLASS.popoverPrimary;
  confirm.textContent = t("popover.retract.confirm");
  confirm.addEventListener("click", () => {
    closePopover();
    onRetract();
  });
  const cancel = document.createElement("button");
  cancel.type = "button";
  cancel.className = CLASS.popoverGhost;
  cancel.textContent = t("popover.cancel");
  cancel.addEventListener("click", closePopover);
  actions.append(confirm, cancel);
  root.replaceChildren(
    el("div", CLASS.popoverTitle, t("popover.retract.title")),
    el("div", CLASS.popoverTarget, t("popover.retract.target", { preview: previewText })),
    el("div", CLASS.popoverImpact, t("popover.retract.hint")),
    actions
  );
  const shell = mountShell(root, anchor, onKeyDown);
  popoverEl = root;
  disposeOutside = shell.dispose;
  focusFirst(root);
}
function openPopover(opts) {
  closePopover();
  if (opts.retract !== void 0) {
    openRetractPopover(opts);
    return;
  }
  const { session, seq, time, preview, anchor, t, chatOf } = opts;
  const onRewind = opts.onRewind;
  if (seq === void 0 || time === void 0 || onRewind === void 0) return;
  const durableOpts = { session, seq, time, preview, anchor, t, chatOf, watchChat: opts.watchChat, onRewind };
  const root = el("div", CLASS.popover);
  root.setAttribute("role", "dialog");
  root.setAttribute("aria-label", t("popover.title"));
  let bothState = { state: "loading" };
  let impactOutcome = null;
  let step = "modes";
  const renderModes = () => {
    step = "modes";
    const children = [
      el("div", CLASS.popoverTitle, t("popover.title")),
      el("div", CLASS.popoverTarget, formatTarget(t, seq, time, preview)),
      modeOption(t("popover.chat"), t("popover.chat.hint"), () => {
        closePopover();
        durableOpts.onRewind("chat");
      })
    ];
    if (bothState.state === "noChanges") {
      children.push(el("div", CLASS.popoverImpact, t("popover.noChanges")));
    } else if (bothState.state === "error") {
      children.push(el("div", CLASS.popoverImpact, t("popover.impact.failed", { message: bothState.message })));
    } else {
      const option = modeOption(
        t("popover.both"),
        bothState.state === "loading" ? t("popover.checking") : t("popover.both.hint"),
        renderImpact
      );
      if (bothState.state === "loading") option.disabled = true;
      children.push(option);
    }
    const actions = el("div", CLASS.popoverActions);
    const cancel = document.createElement("button");
    cancel.type = "button";
    cancel.className = CLASS.popoverGhost;
    cancel.textContent = t("popover.cancel");
    cancel.addEventListener("click", closePopover);
    actions.append(cancel);
    children.push(actions);
    root.replaceChildren(...children);
    focusFirst(root);
  };
  const renderImpact = () => {
    step = "impact";
    renderImpactStep(root, durableOpts, renderModes, impactOutcome);
  };
  const onKeyDown = (event) => {
    if (event.key === "ArrowDown") {
      event.preventDefault();
      event.stopPropagation();
      moveFocus(root, 1);
      return;
    }
    if (event.key === "ArrowUp") {
      event.preventDefault();
      event.stopPropagation();
      moveFocus(root, -1);
      return;
    }
    if (event.key === "Escape") {
      event.preventDefault();
      event.stopPropagation();
      if (step === "impact") renderModes();
      else closePopover();
    }
  };
  renderModes();
  const shell = mountShell(root, anchor, onKeyDown);
  popoverEl = root;
  disposeOutside = shell.dispose;
  void (async () => {
    const outcome = await previewImpact(session, chatOf, seq, (cb) => opts.watchChat(session.sessionId, cb));
    impactOutcome = outcome;
    if (outcome !== null && outcome.kind === "success") {
      bothState = { state: hasFileImpact(outcome.text) ? "hasChanges" : "noChanges" };
    } else {
      bothState = { state: "error", message: outcome?.text ?? "preview command timed out" };
    }
    renderModes();
    shell.position();
  })().catch(() => {
    bothState = { state: "error", message: "unexpected error" };
    renderModes();
    shell.position();
  });
}

// src/client/portals.tsx
var import_react = require("react");
var import_react_dom = require("react-dom");

// src/client/pending.ts
function matchPendingRows(rows, steering) {
  const matched = [];
  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    const item = steering[i];
    if (item !== void 0 && row.text === (item.text ?? "")) {
      matched.push(item.id);
    } else {
      matched.push(null);
    }
  }
  return matched;
}
function retractSpan(steering, targetId) {
  const index = steering.findIndex((item) => item.id === targetId);
  if (index === -1) return [];
  return steering.slice(index).map((item) => item.id);
}

// src/client/portals.tsx
var import_jsx_runtime = require("react/jsx-runtime");
function fillComposerEditable(text) {
  const editable = document.querySelector(COMPOSER_EDITABLE_SELECTOR);
  if (editable === null) return false;
  editable.focus();
  const selection = document.getSelection();
  if (selection !== null) {
    const range = document.createRange();
    range.selectNodeContents(editable);
    selection.removeAllRanges();
    selection.addRange(range);
  }
  let ok = false;
  try {
    ok = document.execCommand("insertText", false, text);
  } catch {
    ok = false;
  }
  if (ok) return true;
  editable.textContent = text;
  editable.dispatchEvent(new Event("input", { bubbles: true }));
  return true;
}
function fillComposer(text) {
  return fillComposerEditable(text);
}
function writeComposer(text, facade) {
  if (facade !== void 0) {
    try {
      facade.setDraft(text);
      return true;
    } catch {
    }
  }
  return fillComposer(text);
}
function userNodeOf(chat, key) {
  const node = chat?.nodes.get(key);
  if (node === void 0 || node.kind !== "user" && node.kind !== "steering") return void 0;
  return node.data;
}
async function runRewindAndFill(session, seq, mode, currentSessionId, chatOf, watchChat, setComposerText) {
  const known = knownCommandSeqs(session, chatOf, (node) => isExecutedRewindCommand(node, seq));
  let result;
  try {
    result = await session.command(`/rewind @${seq} ${mode}`);
  } catch (error) {
    rewindLog.warn("refill", `rewind command threw, skipping refill @${seq}`, error);
    return;
  }
  if (!result.ok) {
    rewindLog.warn("refill", `rewind command rejected for @${seq}`, result.error);
    return;
  }
  if (result.value?.matched !== true) {
    rewindLog.warn("refill", `rewind command was not matched for @${seq}`);
    return;
  }
  let outcome;
  try {
    outcome = await waitForCommand(session, chatOf, (node) => isExecutedRewindCommand(node, seq) && !known.has(node.seq), 2e4, (cb) => watchChat(session.sessionId, cb));
  } catch (error) {
    rewindLog.warn("refill", `waiting for rewind @${seq} outcome threw`, error);
    return;
  }
  if (outcome === null) {
    rewindLog.warn("refill", `rewind @${seq} never settled within timeout, no refill`);
    return;
  }
  if (outcome.kind !== "success") {
    showHint(outcome.text ?? "rewind failed");
    return;
  }
  if (currentSessionId() !== session.sessionId) {
    return;
  }
  let text;
  try {
    text = messageTextAt(chatOf(session), seq);
  } catch (error) {
    rewindLog.warn("refill", `reading target text for @${seq} threw`, error);
    return;
  }
  if (text === void 0 || text === "") {
    return;
  }
  if (composerText().trim() !== "") {
    return;
  }
  try {
    setComposerText(session.sessionId, text);
  } catch (error) {
    rewindLog.warn("refill", `composer refill @${seq} threw`, error);
    return;
  }
}
function composerSurface() {
  return document.querySelector(COMPOSER_EDITABLE_SELECTOR);
}
function showHint(text) {
  const surface = composerSurface();
  const hint = document.createElement("div");
  hint.className = CLASS.guardHint;
  hint.setAttribute("role", "status");
  hint.textContent = text;
  document.body.appendChild(hint);
  if (surface !== null) {
    const card = surface.closest("[data-composer-card]");
    const rect = card instanceof HTMLElement ? card.getBoundingClientRect() : surface.getBoundingClientRect();
    hint.style.left = `${Math.round(rect.left)}px`;
    hint.style.bottom = `${Math.round(window.innerHeight - rect.top + 8)}px`;
  }
  window.setTimeout(() => hint.remove(), 3200);
}
var COMPOSER_EDITABLE_SELECTOR = "[data-composer-input]";
var USER_SEAT_SELECTOR = '[data-chat-flow-kind="user"][data-chat-anchor-key], [data-chat-flow-kind="steering"][data-chat-anchor-key]';
var CHAT_SEAT_SELECTOR = "[data-chat-anchor-key]";
var PENDING_SEAT_SELECTOR = "[data-pending-steering]";
function actionsContainerOf(row) {
  const buttons = Array.from(row?.querySelectorAll("button") ?? []);
  const lastButton = buttons.filter((button) => !button.classList.contains(CLASS.button)).at(-1);
  const structural = lastButton?.parentElement;
  if (structural instanceof HTMLElement && structural.querySelector("button") !== null) return structural;
  return void 0;
}
function collectTargets(chat, hiddenSeqs) {
  const rows = /* @__PURE__ */ new Map();
  for (const element of document.querySelectorAll(USER_SEAT_SELECTOR)) {
    const key = element.dataset.chatAnchorKey;
    if (key !== void 0) rows.set(key, element);
  }
  const targets = [];
  for (const key of chat.order) {
    const node = chat.nodes.get(key);
    if (node === void 0 || node.kind !== "user" && node.kind !== "steering") continue;
    const user = node.data;
    if (hiddenSeqs.has(node.anchorSeq ?? user.seq)) continue;
    const row = rows.get(key);
    const actions = actionsContainerOf(row);
    if (actions === void 0) continue;
    targets.push({ kind: "durable", key, container: actions, seq: user.seq, time: user.time, preview: messagePreviewOf(user) });
  }
  return targets;
}
function isRewindInertSession(snapshot) {
  return snapshot.subagent !== null && snapshot.subagent !== void 0;
}
function collectDurableTargets(snapshot, chat, hiddenSeqs) {
  if (chat === void 0 || isRewindInertSession(snapshot)) return [];
  return collectTargets(chat, hiddenSeqs);
}
function bubbleTextOf(row) {
  const clone = row.cloneNode(true);
  clone.lastElementChild?.remove();
  return clone.textContent ?? "";
}
function collectPendingTargets(snapshot) {
  if (snapshot.subagent !== null) return [];
  const steering = snapshot.queue.filter((item) => item.placement === "steering");
  if (steering.length === 0) return [];
  const rows = Array.from(document.querySelectorAll(PENDING_SEAT_SELECTOR));
  const matched = matchPendingRows(
    rows.map((row) => ({ text: bubbleTextOf(row) })),
    steering.map((item) => ({ id: item.id, text: item.text }))
  );
  const targets = [];
  for (let i = 0; i < matched.length; i++) {
    const itemId = matched[i];
    if (itemId === null) continue;
    const row = rows[i];
    if (row === void 0) continue;
    const actions = actionsContainerOf(row);
    if (actions === void 0) continue;
    const item = steering[i];
    targets.push({
      kind: "pending",
      key: `pending:${itemId}`,
      container: actions,
      itemId,
      text: item.text,
      preview: item.preview
    });
  }
  return targets;
}
function sameTargets(left, right) {
  return left.length === right.length && left.every((target, index) => {
    const other = right[index];
    if (other === void 0 || target.key !== other.key || target.container !== other.container) return false;
    if (target.kind === "durable") return other.kind === "durable" && target.seq === other.seq;
    return other.kind === "pending" && target.itemId === other.itemId;
  });
}
function RewindPortals({ sessionId, sessionOf, chatOf, currentSessionId, watchChat, t, subscribeLocale, setComposerText }) {
  const [targets, setTargets] = (0, import_react.useState)([]);
  const hidden = (0, import_react.useRef)(/* @__PURE__ */ new WeakSet());
  const [, forceRender] = (0, import_react.useReducer)((count) => count + 1, 0);
  (0, import_react.useEffect)(() => subscribeLocale(() => {
    forceRender();
  }), [subscribeLocale]);
  (0, import_react.useLayoutEffect)(() => {
    let active = true;
    let queued = false;
    const refresh = () => {
      if (!active) return;
      const session = sessionOf(sessionId);
      if (session === void 0) {
        setTargets([]);
        return;
      }
      const snapshot = session.getSnapshot();
      const chat = chatOf(session);
      const hiddenSeqs = chat === void 0 ? /* @__PURE__ */ new Set() : hiddenSeqsOf(chat);
      for (const seat of chat === void 0 ? [] : document.querySelectorAll(CHAT_SEAT_SELECTOR)) {
        const key = seat.dataset.chatAnchorKey;
        const anchor = key !== void 0 ? chat?.nodes.get(key)?.anchorSeq : void 0;
        if (anchor !== void 0 && hiddenSeqs.has(anchor)) {
          seat.style.display = "none";
          seat.dataset.dshRewindHidden = "true";
          hidden.current.add(seat);
        } else if (hidden.current.has(seat)) {
          seat.style.display = "";
          delete seat.dataset.dshRewindHidden;
          hidden.current.delete(seat);
        }
      }
      const durable = collectDurableTargets(snapshot, chat, hiddenSeqs);
      const next = [...durable, ...collectPendingTargets(snapshot)];
      setTargets((current) => sameTargets(current, next) ? current : next);
    };
    const queueRefresh = () => {
      if (queued || !active) return;
      queued = true;
      queueMicrotask(() => {
        queued = false;
        refresh();
      });
    };
    refresh();
    const observer = new MutationObserver(queueRefresh);
    observer.observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ["style"] });
    return () => {
      active = false;
      observer.disconnect();
    };
  }, [sessionId, sessionOf]);
  return targets.map((target) => (0, import_react_dom.createPortal)(
    target.kind === "pending" ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      RetractButton,
      {
        target,
        sessionId,
        sessionOf,
        chatOf,
        watchChat,
        setComposerText,
        t
      },
      target.key
    ) : /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      RewindButton,
      {
        target,
        sessionId,
        sessionOf,
        chatOf,
        watchChat,
        currentSessionId,
        setComposerText,
        t
      },
      target.key
    ),
    target.container,
    target.key
  ));
}
function RewindButton({ target, sessionId, sessionOf, chatOf, watchChat, currentSessionId, setComposerText, t }) {
  const onClick = (event) => {
    event.stopPropagation();
    const session = sessionOf(sessionId);
    if (session === void 0) {
      rewindLog.warn("portals", "rewind button clicked with no session binding");
      return;
    }
    const node = userNodeOf(chatOf(session), target.key);
    if (node === void 0) return;
    openPopover({
      session,
      chatOf,
      watchChat,
      seq: node.seq,
      time: node.time,
      preview: messagePreviewOf(node),
      anchor: event.currentTarget,
      t,
      onRewind: (mode) => {
        void runRewindAndFill(session, node.seq, mode, currentSessionId, chatOf, watchChat, setComposerText);
      }
    });
  };
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
    "button",
    {
      type: "button",
      className: CLASS.button,
      "aria-label": t("button.aria"),
      title: t("button.title"),
      onClick,
      dangerouslySetInnerHTML: { __html: REWIND_ICON_SVG }
    }
  );
}
function composerText() {
  const surface = composerSurface();
  if (surface === null) return "";
  return surface.textContent ?? "";
}
async function retractPending(session, itemId, text, setComposerText) {
  const queue = session.getSnapshot().queue;
  const steering = queue.filter((item) => item.placement === "steering");
  let removedTarget = false;
  for (const id of retractSpan(steering, itemId)) {
    let accepted = false;
    try {
      const result = await session.updateQueue(id, { kind: "remove" });
      accepted = result.ok;
      if (!result.ok) rewindLog.info("retract", `pending retract lost the race for ${id}`, result.error);
    } catch (error) {
      rewindLog.warn("retract", `pending retract remove threw for ${id}`, error);
    }
    if (!accepted) break;
    if (id === itemId) removedTarget = true;
  }
  if (removedTarget && text !== null && text !== "" && composerText().trim() === "") {
    setComposerText(session.sessionId, text);
  }
}
function RetractButton({ target, sessionId, sessionOf, chatOf, watchChat, setComposerText, t }) {
  const onClick = (event) => {
    event.stopPropagation();
    const session = sessionOf(sessionId);
    if (session === void 0) return;
    openPopover({
      session,
      chatOf,
      watchChat,
      preview: target.preview,
      anchor: event.currentTarget,
      t,
      retract: { itemId: target.itemId, text: target.text },
      onRetract: () => {
        void retractPending(session, target.itemId, target.text, setComposerText);
      }
    });
  };
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
    "button",
    {
      type: "button",
      className: CLASS.button,
      "aria-label": t("button.retract.aria"),
      title: t("button.retract.title"),
      onClick,
      dangerouslySetInnerHTML: { __html: REWIND_ICON_SVG }
    }
  );
}
function createRewindBridge(deps) {
  return function RewindBridge({ sessionId }) {
    return (0, import_react.createElement)(RewindPortals, { sessionId, ...deps });
  };
}

// src/client/build-info.ts
var PLUGIN_VERSION = true ? "0.12.2" : "dev";
var BUILD_HASH = true ? "c9f4bb5f" : "dev";

// src/client/locales.ts
var zh = {
  "button.aria": "\u56DE\u9000\u5230\u6B64\u6D88\u606F",
  "button.title": "\u56DE\u9000",
  "button.retract.aria": "\u56DE\u9000\u5230\u6B64\u63D2\u8BDD\u6D88\u606F",
  "button.retract.title": "\u56DE\u9000",
  "popover.title": "\u56DE\u9000\u5230\u8FD9\u6761\u6D88\u606F",
  "popover.noText": "\uFF08\u65E0\u6587\u672C\uFF09",
  "popover.retract.title": "\u56DE\u9000\u5230\u8FD9\u6761\u63D2\u8BDD\u6D88\u606F",
  "popover.retract.target": "\u63D2\u8BDD\u4E2D \xB7 {preview}",
  "popover.retract.hint": "\u64A4\u56DE\u8FD9\u6761\u53CA\u4E4B\u540E\u7684\u63D2\u8BDD\u6D88\u606F\uFF0C\u4E0D\u6253\u65AD\u5F53\u524D\u751F\u6210",
  "popover.retract.confirm": "\u786E\u8BA4\u56DE\u9000",
  "popover.chat": "\u4EC5\u56DE\u9000\u5BF9\u8BDD",
  "popover.chat.hint": "\u53EA\u56DE\u9000\u6A21\u578B\u4E0A\u4E0B\u6587\uFF0C\u4E0D\u52A8\u5DE5\u4F5C\u533A\u6587\u4EF6",
  "popover.both": "\u56DE\u9000\u5BF9\u8BDD\u548C\u4EE3\u7801",
  "popover.both.hint": "\u5BF9\u8BDD\u56DE\u9000\u5E76\u8FD8\u539F\u5DE5\u4F5C\u533A\u6587\u4EF6",
  "popover.checking": "\u6B63\u5728\u68C0\u67E5\u6587\u4EF6\u53D8\u66F4\u2026",
  "popover.noChanges": "\u6B64\u6D88\u606F\u4E4B\u540E\u6CA1\u6709\u53EF\u8FD8\u539F\u7684\u6587\u4EF6\u53D8\u66F4\uFF0C\u4EC5\u53EF\u56DE\u9000\u5BF9\u8BDD",
  "popover.cancel": "\u53D6\u6D88",
  "popover.impact.loading": "\u6B63\u5728\u83B7\u53D6\u5F71\u54CD\u6E05\u5355\u2026",
  "popover.impact.failed": "\u65E0\u6CD5\u83B7\u53D6\u5F71\u54CD\u6E05\u5355\uFF1A{message}",
  "popover.impact.none": "\u76EE\u6807\u4E4B\u540E\u6CA1\u6709\u8DDF\u8E2A\u5230\u7684\u5199\u7C7B\u53D8\u66F4\uFF0C\u65E0\u9700\u8FD8\u539F\u6587\u4EF6\u3002",
  "popover.impact.restore": "\u8FD8\u539F {path}",
  "popover.impact.delete": "\u5220\u9664 {path}",
  "popover.confirm": "\u786E\u8BA4\u56DE\u9000",
  "popover.back": "\u8FD4\u56DE",
  "cleanup.title": "\u5FEB\u7167\u6E05\u7406",
  "cleanup.desc": "dsh-rewind \xB7 \u7BA1\u7406\u4F1A\u8BDD\u5FEB\u7167\u5907\u4EFD\u7684\u81EA\u52A8\u6E05\u7406\u7B56\u7565",
  "cleanup.expand": "\u5C55\u5F00",
  "cleanup.collapse": "\u6536\u8D77",
  "cleanup.unsaved": "\u672A\u4FDD\u5B58\u4FEE\u6539",
  "cleanup.auto": "\u81EA\u52A8\u6E05\u7406",
  "cleanup.auto.on": "\u5F00\u542F\u540E\u6309\u4E0D\u6D3B\u8DC3\u5929\u6570\u81EA\u52A8\u6E05\u7406\u8FC7\u671F\u4F1A\u8BDD\u5FEB\u7167",
  "cleanup.auto.off": "\u5173\u95ED\u540E\u4FDD\u7559\u5168\u90E8\u5FEB\u7167\uFF0C\u4E0D\u81EA\u52A8\u6E05\u7406",
  "cleanup.maxAge": "\u4E0D\u6D3B\u8DC3\u65F6\u95F4\uFF08\u5929\uFF09",
  "cleanup.maxAge.hint": "\u8D85\u8FC7\u8BE5\u5929\u6570\u672A\u6D3B\u52A8\u7684\u4F1A\u8BDD\u5FEB\u7167\u4F1A\u88AB\u6E05\u7406",
  "cleanup.invalid": "\u4EC5\u63A5\u53D7\u6B63\u6574\u6570",
  "cleanup.discard": "\u653E\u5F03\u4FEE\u6539",
  "cleanup.save": "\u4FDD\u5B58",
  "cleanup.saving": "\u4FDD\u5B58\u4E2D\u2026",
  "cleanup.saved": "\u5DF2\u4FDD\u5B58\u5E76\u751F\u6548",
  "cleanup.saveFailed": "\u4FDD\u5B58\u5931\u8D25\uFF1A{message}",
  "cleanup.readonly": "\u8BBE\u7F6E\u6E90\u53EA\u8BFB"
};
var en = {
  "button.aria": "Rewind to this message",
  "button.title": "Rewind",
  "button.retract.aria": "Rewind to this pending message",
  "button.retract.title": "Rewind",
  "popover.title": "Rewind to this message",
  "popover.noText": "(no text)",
  "popover.retract.title": "Rewind to this pending message",
  "popover.retract.target": "Pending \xB7 {preview}",
  "popover.retract.hint": "Retracts this pending message and the ones after it, without interrupting the run",
  "popover.retract.confirm": "Confirm rewind",
  "popover.chat": "Rewind conversation only",
  "popover.chat.hint": "Cut the model context only; workspace files stay untouched",
  "popover.both": "Rewind conversation and code",
  "popover.both.hint": "Cut the context and restore workspace files",
  "popover.checking": "Checking for file changes\u2026",
  "popover.noChanges": "No tracked file changes after this message; conversation-only rewind",
  "popover.cancel": "Cancel",
  "popover.impact.loading": "Fetching impact list\u2026",
  "popover.impact.failed": "Could not fetch the impact list: {message}",
  "popover.impact.none": "No tracked file changes after the target; nothing to restore.",
  "popover.impact.restore": "Restore {path}",
  "popover.impact.delete": "Delete {path}",
  "popover.confirm": "Confirm rewind",
  "popover.back": "Back",
  "cleanup.title": "Snapshot cleanup",
  "cleanup.desc": "dsh-rewind \xB7 Manage the auto-cleanup policy of session snapshot backups",
  "cleanup.expand": "Expand",
  "cleanup.collapse": "Collapse",
  "cleanup.unsaved": "Unsaved changes",
  "cleanup.auto": "Auto cleanup",
  "cleanup.auto.on": "When enabled, session snapshots idle past the cutoff are cleaned automatically",
  "cleanup.auto.off": "When disabled, all snapshot backups are kept; nothing is cleaned automatically.",
  "cleanup.maxAge": "Idle time (days)",
  "cleanup.maxAge.hint": "Snapshot backups of sessions idle longer than this many days are cleaned",
  "cleanup.invalid": "A positive integer only",
  "cleanup.discard": "Discard changes",
  "cleanup.save": "Save",
  "cleanup.saving": "Saving\u2026",
  "cleanup.saved": "Saved and applied",
  "cleanup.saveFailed": "Save failed: {message}",
  "cleanup.readonly": "Read-only settings source"
};

// src/client/settings-card.tsx
var import_react2 = require("react");
var import_jsx_runtime2 = require("react/jsx-runtime");
var CLEANUP_SETTINGS_NAMESPACE = "dsh-rewind-snapshot-cleanup";
var DEFAULT_MAX_AGE_DAYS = 30;
function draftFrom(policy) {
  return { enabled: policy?.enabled ?? false, maxAgeDays: String(policy?.maxAgeDays ?? "") };
}
function maxAgeOf(text) {
  const trimmed = text.trim();
  if (!/^\d+$/.test(trimmed)) return null;
  const days = Number(trimmed);
  return Number.isSafeInteger(days) && days > 0 ? days : null;
}
function configOf(draft) {
  const days = maxAgeOf(draft.maxAgeDays);
  if (days === null) return null;
  return { enabled: draft.enabled, maxAgeDays: days };
}
function dirtyOf(base, draft) {
  return base.enabled !== draft.enabled || base.maxAgeDays !== draft.maxAgeDays;
}
function SettingsCleanupCard({ api, t }) {
  const [open, setOpen] = (0, import_react2.useState)(false);
  const [baseline, setBaseline] = (0, import_react2.useState)(() => draftFrom(api.read()));
  const [draft, setDraft] = (0, import_react2.useState)(() => draftFrom(api.read()));
  const [busy, setBusy] = (0, import_react2.useState)(false);
  const [error, setError] = (0, import_react2.useState)(null);
  const writable = api.writable();
  (0, import_react2.useEffect)(() => api.subscribe(() => {
    const next = draftFrom(api.read());
    setBaseline((base) => {
      setDraft((cur) => dirtyOf(base, cur) ? cur : next);
      return next;
    });
  }), [api]);
  const dirty = dirtyOf(baseline, draft);
  const days = maxAgeOf(draft.maxAgeDays);
  const invalid = days === null;
  const disabled = busy || !writable;
  const edit = (patch) => {
    setDraft((cur) => ({ ...cur, ...patch }));
    setError(null);
  };
  const save = async () => {
    if (busy || !writable || !dirty) return;
    const next = configOf(draft);
    if (next === null) {
      setError(t("cleanup.invalid"));
      return;
    }
    setBusy(true);
    setError(null);
    try {
      await api.save(next);
      setBaseline(draft);
      setError(null);
    } catch (e) {
      setError(t("cleanup.saveFailed", { message: e instanceof Error ? e.message : String(e) }));
    } finally {
      setBusy(false);
    }
  };
  const discard = () => {
    if (busy) return;
    setDraft(baseline);
    setError(null);
  };
  return /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("li", { className: `dsh-rewind-cleanup-card${open ? " dsh-rewind-cleanup-card-open" : ""}`, children: [
    /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)(
      "button",
      {
        type: "button",
        className: "dsh-rewind-cleanup-header",
        "aria-expanded": open,
        "aria-label": `${t(open ? "cleanup.collapse" : "cleanup.expand")}: ${t("cleanup.title")}`,
        onClick: () => setOpen(!open),
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("span", { className: "dsh-rewind-cleanup-head-text", children: [
            /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("span", { className: "dsh-rewind-cleanup-name", children: t("cleanup.title") }),
            /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("span", { className: "dsh-rewind-cleanup-desc", children: t("cleanup.desc") })
          ] }),
          dirty ? /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("span", { className: "dsh-rewind-cleanup-pending", children: t("cleanup.unsaved") }) : null,
          /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(
            "svg",
            {
              className: `dsh-rewind-cleanup-chevron${open ? " dsh-rewind-cleanup-chevron-open" : ""}`,
              width: "14",
              height: "14",
              viewBox: "0 0 16 16",
              "aria-hidden": "true",
              children: /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("path", { d: "M4 6l4 4 4-4", fill: "none", stroke: "currentColor", strokeWidth: "1.5", strokeLinecap: "round", strokeLinejoin: "round" })
            }
          )
        ]
      }
    ),
    open ? /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("div", { className: "dsh-rewind-cleanup-body", children: [
      !writable ? /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("p", { className: "dsh-rewind-cleanup-readonly", role: "status", children: t("cleanup.readonly") }) : null,
      /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("div", { className: "dsh-rewind-cleanup-permission", children: [
        /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("div", { className: "dsh-rewind-cleanup-toggle-row", children: [
          /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("span", { className: "dsh-rewind-cleanup-toggle-label", id: "dsh-rewind-cleanup-enabled-label", children: t("cleanup.auto") }),
          /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(
            "button",
            {
              type: "button",
              role: "switch",
              className: "dsh-rewind-cleanup-switch",
              "aria-checked": draft.enabled,
              "aria-labelledby": "dsh-rewind-cleanup-enabled-label",
              disabled,
              onClick: () => edit({ enabled: !draft.enabled }),
              children: /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("span", { className: "dsh-rewind-cleanup-thumb" })
            }
          )
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("p", { className: "dsh-rewind-cleanup-hint", children: t(draft.enabled ? "cleanup.auto.on" : "cleanup.auto.off") })
      ] }),
      draft.enabled ? /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("div", { className: "dsh-rewind-cleanup-field", children: [
        /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("div", { className: "dsh-rewind-cleanup-head", children: /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("label", { className: "dsh-rewind-cleanup-label", htmlFor: "dsh-rewind-cleanup-maxage", children: t("cleanup.maxAge") }) }),
        /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(
          "input",
          {
            className: `dsh-rewind-cleanup-input${invalid ? " dsh-rewind-cleanup-input-invalid" : ""}`,
            type: "text",
            inputMode: "numeric",
            id: "dsh-rewind-cleanup-maxage",
            value: draft.maxAgeDays,
            disabled,
            "aria-invalid": invalid || void 0,
            placeholder: String(DEFAULT_MAX_AGE_DAYS),
            onChange: (e) => edit({ maxAgeDays: e.target.value })
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("p", { className: invalid ? "dsh-rewind-cleanup-error" : "dsh-rewind-cleanup-hint", children: invalid ? t("cleanup.invalid") : t("cleanup.maxAge.hint") })
      ] }) : null,
      /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("div", { className: "dsh-rewind-cleanup-footer", children: [
        error ? /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("p", { className: "dsh-rewind-cleanup-failed", role: "status", children: error }) : null,
        /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(
          "button",
          {
            type: "button",
            className: "dsh-rewind-cleanup-discard",
            disabled: !dirty || busy || !writable,
            onClick: discard,
            children: t("cleanup.discard")
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(
          "button",
          {
            type: "button",
            className: "dsh-rewind-cleanup-save",
            disabled: !dirty || busy || !writable || invalid,
            onClick: save,
            children: busy ? t("cleanup.saving") : t("cleanup.save")
          }
        )
      ] })
    ] }) : null
  ] });
}

// src/client/index.ts
var name = "dsh-rewind";
var inject = ["slots", "sessions", "locale", "commandUi"];
var NS2 = "rewind";
var HEADER_ACTIONS_SLOT = "conversation.session.header.actions";
var COMPOSER_EDITABLE_SELECTOR2 = "[data-composer-input]";
function apply(ctx) {
  rewindLog.info("boot", `loaded v${PLUGIN_VERSION} (build ${BUILD_HASH})`);
  ctx.effect(function* () {
    yield ctx.locale.register(NS2, { zh, en });
    const t = ctx.locale.bind(NS2);
    const style = document.createElement("style");
    style.dataset.plugin = "dsh-rewind";
    style.textContent = STYLE;
    document.head.appendChild(style);
    const sessionOf = (sessionId) => ctx.sessions.binding(sessionId)?.session;
    const currentSessionId = () => ctx.sessions.list.getSnapshot().current;
    const subscribeLocale = (cb) => ctx.locale.subscribe(cb);
    const uiConversation = () => ctx.get("uiConversation");
    const CHAT_VIEW = "chat";
    const chatOf = (session) => {
      if (session === void 0) return void 0;
      try {
        const view = uiConversation()?.binding(session.sessionId).target(CHAT_VIEW);
        return chatSnapshotOf(view);
      } catch {
        return void 0;
      }
    };
    const setComposerText = (sessionId, text) => {
      try {
        const conversation = ctx.get("conversation");
        const input = conversation?.input;
        const scope = ctx.sessions.scope?.(sessionId);
        const facade = input !== void 0 && scope !== void 0;
        const ok = writeComposer(
          text,
          facade ? { setDraft: (draft) => {
            input.for(scope).setDraft(draft);
          } } : void 0
        );
        return ok;
      } catch (error) {
        rewindLog.warn("refill", "composer write threw", error);
        return false;
      }
    };
    const watchChat = (sessionId, cb) => resolveChatWatch(
      (id) => {
        try {
          return uiConversation()?.binding(id).target(CHAT_VIEW);
        } catch {
          return void 0;
        }
      },
      sessionId,
      cb
    );
    const slots = ctx.slots;
    yield slots.inject(HEADER_ACTIONS_SLOT, () => slots.register(
      {
        name: HEADER_ACTIONS_SLOT,
        // A distinct list-entry id keeps the bridge from shadowing any other
        // header action; the entry renders portals only, never header UI.
        id: "dsh-rewind-portals",
        order: 1e3
      },
      createRewindBridge({ sessionOf, chatOf, currentSessionId, watchChat, setComposerText, t, subscribeLocale })
    ));
    const clientCtx = ctx;
    clientCtx.inject(["settingsScope"], (scoped) => {
      try {
        const scope = scoped.settingsScope.bind({ namespace: CLEANUP_SETTINGS_NAMESPACE });
        const cardApi = {
          read: () => {
            const value = scope.getSnapshot().value;
            return value === void 0 ? void 0 : { enabled: value.enabled, maxAgeDays: value.maxAgeDays };
          },
          writable: () => {
            return scope.getSnapshot().writable === true;
          },
          save: async (next) => {
            await scope.set("enabled", next.enabled);
            await scope.set("maxAgeDays", next.maxAgeDays);
          },
          subscribe: (cb) => scope.subscribe(cb)
        };
        scoped.slots.inject("settings.plugin.item", () => scoped.slots.register(
          {
            name: "settings.plugin.item",
            key: CLEANUP_SETTINGS_NAMESPACE,
            // Match the official cards / dsh-market: locale + inject provide
            // the card its props through the slot renderer (the keyed card owns
            // its internals, but the page feeds it locale + the bound api).
            locale: NS2,
            inject: () => ({ t, api: cardApi })
          },
          SettingsCleanupCard
        ));
      } catch (error) {
        rewindLog.error("settings", "settings card register failed", error);
      }
    });
    const commandUi = ctx.get("commandUi");
    const hasCandidates = (sessionId) => {
      const face = sessionId === void 0 ? void 0 : sessionOf(sessionId);
      if (face === void 0 || isRewindInertSession(face.getSnapshot())) return false;
      const chat = chatOf(face);
      return chat !== void 0 && rewindCandidatesOfChat(chat).length > 0;
    };
    const fetchHostCandidates = async (face, chatOf2) => {
      const known = knownCommandSeqs(face, chatOf2, (node) => isCandidateCommand(node));
      const result = await face.command("/rewind __candidates");
      if (!result.ok || result.value?.matched !== true) return void 0;
      const outcome = await waitForCommand(face, chatOf2, (node) => isCandidateCommand(node) && !known.has(node.seq), 8e3, (cb) => watchChat(face.sessionId, cb));
      if (outcome === null || outcome.kind !== "success" || outcome.text === void 0) return void 0;
      return rewindCandidatesFromHostText(outcome.text);
    };
    const hostCandidatesCache = /* @__PURE__ */ new Map();
    const composerAnchor = () => {
      const surface = composerSurface2();
      const card = surface?.closest("[data-composer-card]");
      return card ?? surface ?? document.body;
    };
    const rewindPopupSpec = {
      // The picker exists exactly while the surface has a reachable user
      // message: a fresh session (no candidates) falls through to the host
      // command, which fails with "no user messages" — matching the harness's
      // own decoration convention (see ui-permission-presets).
      available: (session) => hasCandidates(session.sessionId),
      ui: {
        kind: "popupSelect",
        options: async (session) => {
          const face = sessionOf(session.sessionId);
          if (face === void 0) return [];
          const candidates = await fetchHostCandidates(face, chatOf);
          if (candidates !== void 0) hostCandidatesCache.set(session.sessionId, candidates);
          return candidates === void 0 ? [] : rewindOptionsFromCandidates(candidates, t);
        },
        onSelect: (option, session) => {
          const face = sessionOf(session.sessionId);
          if (face === void 0) return;
          const candidate = hostCandidatesCache.get(session.sessionId)?.find(
            (candidate2) => candidate2.seq === Number(option.id)
          );
          if (candidate === void 0) return;
          openPopover({
            session: face,
            chatOf,
            watchChat,
            seq: candidate.seq,
            time: candidate.time,
            preview: candidate.preview,
            anchor: composerAnchor(),
            t,
            onRewind: (mode) => {
              void runRewindAndFill(face, candidate.seq, mode, currentSessionId, chatOf, watchChat, setComposerText);
            }
          });
        }
      }
    };
    for (const name2 of ["rewind", "undo"]) {
      yield commandUi.decorate({ name: name2, ...rewindPopupSpec });
    }
    const composerSurface2 = () => document.querySelector(COMPOSER_EDITABLE_SELECTOR2);
    yield () => {
      style.remove();
    };
  }, "dsh-rewind client lifecycle");
}

    return module.exports;
  }
});
